package com.github.microwww.security.serve.domain;

import java.util.*;
import javax.persistence.*;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(name = "role")
public class Role extends AbstractBasicEntity {

    @Basic
    @Column(nullable = false, length = 45)
    private String name;

    @Basic
    private String description;

    @Basic
    @Column(name = "create_time", columnDefinition = "TIMESTAMP", nullable = false)
    private Date createTime;

    @ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.MERGE)
    @JoinColumn(name = "webapp_id", columnDefinition = "INT")
    private Webapp webapp;

    @OneToMany(targetEntity = RoleAccount.class, mappedBy = "role", cascade = CascadeType.MERGE)
    private List<RoleAccount> roleAccounts;

    @OneToMany(targetEntity = RoleAuthority.class, mappedBy = "role", cascade = CascadeType.MERGE)
    private List<RoleAuthority> roleAuthoritys;

    public Role() {
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public List<RoleAccount> getRoleAccounts() {
        return roleAccounts;
    }

    public void setRoleAccounts(List<RoleAccount> roleAccounts) {
        this.roleAccounts = roleAccounts;
    }

    public List<RoleAuthority> getRoleAuthoritys() {
        return roleAuthoritys;
    }

    public void setRoleAuthoritys(List<RoleAuthority> roleAuthoritys) {
        this.roleAuthoritys = roleAuthoritys;
    }

    public Webapp getWebapp() {
        return webapp;
    }

    public void setWebapp(Webapp webapp) {
        this.webapp = webapp;
    }
}
