package com.github.microwww.security.serve.domain;

import javax.persistence.*;
import java.util.List;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(name = "role")
public class Role extends AbstractBasicEntity {

    @Basic
    @Column(nullable = false, length = 45)
    private String name;

    @Basic
    private String description;

    @ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.MERGE)
    @JoinColumn(name = "webapp_id", columnDefinition = "INT")
    private Webapp webapp;

    @OneToMany(targetEntity = RoleAccount.class, mappedBy = "role", cascade = CascadeType.MERGE)
    private List<RoleAccount> roleAccounts;

    @OneToMany(targetEntity = RolePermission.class, mappedBy = "role", cascade = CascadeType.MERGE)
    private List<RolePermission> rolePermissions;

    public Role() {
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public List<RoleAccount> getRoleAccounts() {
        return roleAccounts;
    }

    public void setRoleAccounts(List<RoleAccount> roleAccounts) {
        this.roleAccounts = roleAccounts;
    }

    public List<RolePermission> getRolePermissions() {
        return rolePermissions;
    }

    public void setRolePermissions(List<RolePermission> roleAuthoritys) {
        this.rolePermissions = roleAuthoritys;
    }

    public Webapp getWebapp() {
        return webapp;
    }

    public void setWebapp(Webapp webapp) {
        this.webapp = webapp;
    }
}
