package com.github.microwww.security.serve.domain;

import java.util.*;
import javax.persistence.*;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(name = "webapp")
public class Webapp extends AbstractBasicEntity {
    private static final long serialVersionUID = 1L;

    @Basic
    @Column(name = "app_id", nullable = false)
    private String appId;

    @Basic
    @Column(name = "app_security", nullable = false)
    private String appSecurity;

    @Basic
    @Column(nullable = false)
    private String name;

    @Basic
    @Column(name = "all_login")
    private boolean allLogin;

    @Basic
    private boolean disable;

    @Basic
    private String description;

    @OneToMany(targetEntity = Permission.class, mappedBy = "webapp", cascade = CascadeType.MERGE)
    private List<Permission> permissions;

    @ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.MERGE)
    @JoinColumn(name = "role_id", columnDefinition = "INT")
    private Role role;

    public Webapp() {
    }

    public boolean isAllLogin() {
        return allLogin;
    }

    public void setAllLogin(boolean allLogin) {
        this.allLogin = allLogin;
    }

    public String getAppId() {
        return appId;
    }

    public void setAppId(String appId) {
        this.appId = appId;
    }

    public String getAppSecurity() {
        return appSecurity;
    }

    public void setAppSecurity(String appSecurity) {
        this.appSecurity = appSecurity;
    }

    public List<Permission> getPermissions() {
        return permissions;
    }

    public void setPermissions(List<Permission> authoritys) {
        this.permissions = authoritys;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Role getRole() {
        return role;
    }

    public void setRole(Role role) {
        this.role = role;
    }

    public boolean isDisable() {
        return disable;
    }

    public void setDisable(boolean disable) {
        this.disable = disable;
    }
}
