######

#
server:
  tomcat:
    accept-count: 500
    max-connections: 500
    uri-encoding: UTF-8
    threads:
      max: 500
#    remoteip:
#      port-header: X-Forwarded-Port
#      protocol-header: X-Forwarded-Proto
#      remote-ip-header: X-Forwarded-For
#
spring:
  profiles:
    active: dev
  application:
    name: url-security
  data:
    redis:
      repositories:
        enabled: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: true
      connection-test-query: SELECT 1
      connection-timeout: 30000
      idle-timeout: 300000
      max-lifetime: 600000
      maximum-pool-size: 15
      minimum-idle: 5
      pool-name: HikariPool
    type: com.zaxxer.hikari.HikariDataSource
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  jpa:
    generate-ddl: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        #ddl-auto: update
    show-sql: false
  redis:
    port: 6379
    database: 0
    timeout: 30s
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        max-wait: 30s
        min-idle: 10
      shutdown-timeout: 5s
  security:
    user:
      password: f6056c42-15df-4783-a2bc-6689a2389f77
  messages:
    basename: i18n/messages
    encoding: UTF-8
  mail:
    protocol: smtp
    port: 25
    test-connection: false
    default-encoding: UTF-8
  servlet:
    multipart:
      maxFileSize: 500MB
      maxRequestSize: 500MB
##
logging:
  root: info
  level:
    com.github.microwww.security.serve.SecurityApplication: info
#
